### ISSUE TITLE
Investigate whether rights-app startup scripts are working properly after reboot

### ISSUE THREAD

**Issue by anarchivist** [rightsstatements/rights-deploy#13] opened 2016-06-20 13:16 UTC
See rightsstatements/rightsstatements.github.io#64. We saw 503 errors after `rights-prod` rebooted; we should ensure that the application starts up properly upon reboot.

**Comment by anarchivist** [comment] 2016-06-21 19:35
Hi @literarymachine - I confirmed (on `rights-stg`) that after reboot the rights app doesn't start automatically. Please look into this when you get a moment - thanks!

**Comment by literarymachine** [comment] 2016-06-21 19:54
@anarchivist cannot reproduce this locally and on dev where the startup script brings the app back fine. Weird thing is that after the server upgrade some time ago, which involved a reboot, the app started up properly. I am travelling this week but will look into it beginning of next!

**Comment by anarchivist** [comment] 2016-06-22 12:33
@literarymachine No worries - let's touch base at the beginning of next week once you're back. Hope the rest of you travel goes well.

**Comment by literarymachine** [comment] 2016-06-27 16:37
The error was not reproducible when using `sudo shutdown -r now` or `sudo reboot`. In both cases the app came back up immediately. Closing this as discussed with @anarchivist.

**Closed as completed** 2016-06-27 16:38 UTC
Labels: bug, wontfix
